export const CAMPAIGN_CREATE = 'CAMPAIGN_CREATE';
export const CAMPAIGN_LIST = 'CAMPAIGN_LIST';
export const CAMPAIGN_START = 'CAMPAIGN_START';
export const CAMPAIGN_STOP = 'CAMPAIGN_STOP';
export const CAMPAIGN_CHANGE_STATUS = 'CAMPAIGN_CHANGE_STATUS';
export const CAMPAIGN_HISTORY = 'CAMPAIGN_HISTORY';
