export const CONTACTS_UPLOAD_PHONES = 'CONTACTS_UPLOAD_PHONES';
export const CONTACTS_IMPORT_PHONES = 'CONTACTS_IMPORT_PHONES';
export const CONTACTS_GET_PHONES = 'CONTACTS_GET_PHONES';
export const CONTACTS_CLEAR_PHONES = 'CONTACTS_CLEAR_PHONES';
export const CONTACTS_CLEAR_BASE = 'CONTACTS_CLEAR_BASE';
export const CONTACTS_GET_LIST = 'CONTACTS_GET_LIST';
