export const PROJECT_LIST = 'PROJECT_LIST';
export const PROJECT_CHANGE_STATUS = 'PROJECT_CHANGE_STATUS';
export const PROJECT_ACTIVATE = 'PROJECT_ACTIVATE';
export const PROJECT_ARCHIVE = 'PROJECT_ARCHIVE';
export const PROJECT_CREATE = 'PROJECT_CREATE';
export const PROJECT_EDIT = 'PROJECT_EDIT';
export const PROJECT_FORM = 'PROJECT_FORM';
export const SET_PROJECT = 'SET_PROJECT';
