export const SCRIPTS_UPLOAD = 'SCRIPTS_UPLOAD';
export const SCRIPTS_UPLOAD_PHRASES = 'SCRIPTS_UPLOAD_PHRASES';
export const SCRIPTS_LIST = 'SCRIPTS_LIST';
export const SCRIPTS_CLEAR_PHONES = 'SCRIPTS_CLEAR_PHONES';
